package geo

import (
	"context"
	"github.com/flipped-aurora/gin-vue-admin/server/plugin/geo/model"
	"github.com/flipped-aurora/gin-vue-admin/server/service/system"
	"github.com/pkg/errors"
	"gorm.io/gorm"
)

//
//geo_areas
//geo_provinces

type initCity struct{}

const initOrderCity = initOrderArea + 1

// auto run
func init() {
	system.RegisterInit(initOrderCity, &initCity{})
}

func (i initCity) InitializerName() string {
	return model.City{}.TableName()
}

func (i *initCity) MigrateTable(ctx context.Context) (context.Context, error) {
	db, ok := ctx.Value("db").(*gorm.DB)
	if !ok {
		return ctx, system.ErrMissingDBContext
	}
	return ctx, db.AutoMigrate(&model.City{})
}

func (i *initCity) TableCreated(ctx context.Context) bool {
	db, ok := ctx.Value("db").(*gorm.DB)
	if !ok {
		return false
	}
	return db.Migrator().HasTable(&model.City{})
}

func (i *initCity) InitializeData(ctx context.Context) (context.Context, error) {
	db, ok := ctx.Value("db").(*gorm.DB)
	if !ok {
		return ctx, system.ErrMissingDBContext
	}
	entities := []model.City{

		{Name: "市辖区", ProvinceCode: "11", Level: 1, Code: "1101", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "11"},
		{Name: "市辖区", ProvinceCode: "12", Level: 1, Code: "1201", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "12"},
		{Name: "石家庄市", ProvinceCode: "13", Level: 1, Code: "1301", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "13"},
		{Name: "唐山市", ProvinceCode: "13", Level: 1, Code: "1302", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "13"},
		{Name: "秦皇岛市", ProvinceCode: "13", Level: 1, Code: "1303", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "13"},
		{Name: "邯郸市", ProvinceCode: "13", Level: 1, Code: "1304", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "13"},
		{Name: "邢台市", ProvinceCode: "13", Level: 1, Code: "1305", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "13"},
		{Name: "保定市", ProvinceCode: "13", Level: 1, Code: "1306", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "13"},
		{Name: "张家口市", ProvinceCode: "13", Level: 1, Code: "1307", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "13"},
		{Name: "承德市", ProvinceCode: "13", Level: 1, Code: "1308", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "13"},
		{Name: "沧州市", ProvinceCode: "13", Level: 1, Code: "1309", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "13"},
		{Name: "廊坊市", ProvinceCode: "13", Level: 1, Code: "1310", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "13"},
		{Name: "衡水市", ProvinceCode: "13", Level: 1, Code: "1311", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "13"},
		{Name: "太原市", ProvinceCode: "14", Level: 1, Code: "1401", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "14"},
		{Name: "大同市", ProvinceCode: "14", Level: 1, Code: "1402", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "14"},
		{Name: "阳泉市", ProvinceCode: "14", Level: 1, Code: "1403", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "14"},
		{Name: "长治市", ProvinceCode: "14", Level: 1, Code: "1404", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "14"},
		{Name: "晋城市", ProvinceCode: "14", Level: 1, Code: "1405", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "14"},
		{Name: "朔州市", ProvinceCode: "14", Level: 1, Code: "1406", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "14"},
		{Name: "晋中市", ProvinceCode: "14", Level: 1, Code: "1407", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "14"},
		{Name: "运城市", ProvinceCode: "14", Level: 1, Code: "1408", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "14"},
		{Name: "忻州市", ProvinceCode: "14", Level: 1, Code: "1409", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "14"},
		{Name: "临汾市", ProvinceCode: "14", Level: 1, Code: "1410", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "14"},
		{Name: "吕梁市", ProvinceCode: "14", Level: 1, Code: "1411", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "14"},
		{Name: "呼和浩特市", ProvinceCode: "15", Level: 1, Code: "1501", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "15"},
		{Name: "包头市", ProvinceCode: "15", Level: 1, Code: "1502", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "15"},
		{Name: "乌海市", ProvinceCode: "15", Level: 1, Code: "1503", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "15"},
		{Name: "赤峰市", ProvinceCode: "15", Level: 1, Code: "1504", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "15"},
		{Name: "通辽市", ProvinceCode: "15", Level: 1, Code: "1505", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "15"},
		{Name: "鄂尔多斯市", ProvinceCode: "15", Level: 1, Code: "1506", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "15"},
		{Name: "呼伦贝尔市", ProvinceCode: "15", Level: 1, Code: "1507", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "15"},
		{Name: "巴彦淖尔市", ProvinceCode: "15", Level: 1, Code: "1508", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "15"},
		{Name: "乌兰察布市", ProvinceCode: "15", Level: 1, Code: "1509", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "15"},
		{Name: "兴安盟", ProvinceCode: "15", Level: 1, Code: "1522", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "15"},
		{Name: "锡林郭勒盟", ProvinceCode: "15", Level: 1, Code: "1525", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "15"},
		{Name: "阿拉善盟", ProvinceCode: "15", Level: 1, Code: "1529", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "15"},
		{Name: "沈阳市", ProvinceCode: "21", Level: 1, Code: "2101", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "21"},
		{Name: "大连市", ProvinceCode: "21", Level: 1, Code: "2102", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "21"},
		{Name: "鞍山市", ProvinceCode: "21", Level: 1, Code: "2103", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "21"},
		{Name: "抚顺市", ProvinceCode: "21", Level: 1, Code: "2104", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "21"},
		{Name: "本溪市", ProvinceCode: "21", Level: 1, Code: "2105", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "21"},
		{Name: "丹东市", ProvinceCode: "21", Level: 1, Code: "2106", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "21"},
		{Name: "锦州市", ProvinceCode: "21", Level: 1, Code: "2107", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "21"},
		{Name: "营口市", ProvinceCode: "21", Level: 1, Code: "2108", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "21"},
		{Name: "阜新市", ProvinceCode: "21", Level: 1, Code: "2109", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "21"},
		{Name: "辽阳市", ProvinceCode: "21", Level: 1, Code: "2110", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "21"},
		{Name: "盘锦市", ProvinceCode: "21", Level: 1, Code: "2111", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "21"},
		{Name: "铁岭市", ProvinceCode: "21", Level: 1, Code: "2112", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "21"},
		{Name: "朝阳市", ProvinceCode: "21", Level: 1, Code: "2113", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "21"},
		{Name: "葫芦岛市", ProvinceCode: "21", Level: 1, Code: "2114", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "21"},
		{Name: "长春市", ProvinceCode: "22", Level: 1, Code: "2201", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "22"},
		{Name: "吉林市", ProvinceCode: "22", Level: 1, Code: "2202", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "22"},
		{Name: "四平市", ProvinceCode: "22", Level: 1, Code: "2203", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "22"},
		{Name: "辽源市", ProvinceCode: "22", Level: 1, Code: "2204", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "22"},
		{Name: "通化市", ProvinceCode: "22", Level: 1, Code: "2205", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "22"},
		{Name: "白山市", ProvinceCode: "22", Level: 1, Code: "2206", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "22"},
		{Name: "松原市", ProvinceCode: "22", Level: 1, Code: "2207", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "22"},
		{Name: "白城市", ProvinceCode: "22", Level: 1, Code: "2208", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "22"},
		{Name: "延边朝鲜族自治州", ProvinceCode: "22", Level: 1, Code: "2224", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "22"},
		{Name: "哈尔滨市", ProvinceCode: "23", Level: 1, Code: "2301", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "23"},
		{Name: "齐齐哈尔市", ProvinceCode: "23", Level: 1, Code: "2302", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "23"},
		{Name: "鸡西市", ProvinceCode: "23", Level: 1, Code: "2303", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "23"},
		{Name: "鹤岗市", ProvinceCode: "23", Level: 1, Code: "2304", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "23"},
		{Name: "双鸭山市", ProvinceCode: "23", Level: 1, Code: "2305", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "23"},
		{Name: "大庆市", ProvinceCode: "23", Level: 1, Code: "2306", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "23"},
		{Name: "伊春市", ProvinceCode: "23", Level: 1, Code: "2307", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "23"},
		{Name: "佳木斯市", ProvinceCode: "23", Level: 1, Code: "2308", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "23"},
		{Name: "七台河市", ProvinceCode: "23", Level: 1, Code: "2309", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "23"},
		{Name: "牡丹江市", ProvinceCode: "23", Level: 1, Code: "2310", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "23"},
		{Name: "黑河市", ProvinceCode: "23", Level: 1, Code: "2311", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "23"},
		{Name: "绥化市", ProvinceCode: "23", Level: 1, Code: "2312", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "23"},
		{Name: "大兴安岭地区", ProvinceCode: "23", Level: 1, Code: "2327", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "23"},
		{Name: "市辖区", ProvinceCode: "31", Level: 1, Code: "3101", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "31"},
		{Name: "南京市", ProvinceCode: "32", Level: 1, Code: "3201", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "32"},
		{Name: "无锡市", ProvinceCode: "32", Level: 1, Code: "3202", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "32"},
		{Name: "徐州市", ProvinceCode: "32", Level: 1, Code: "3203", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "32"},
		{Name: "常州市", ProvinceCode: "32", Level: 1, Code: "3204", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "32"},
		{Name: "苏州市", ProvinceCode: "32", Level: 1, Code: "3205", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "32"},
		{Name: "南通市", ProvinceCode: "32", Level: 1, Code: "3206", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "32"},
		{Name: "连云港市", ProvinceCode: "32", Level: 1, Code: "3207", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "32"},
		{Name: "淮安市", ProvinceCode: "32", Level: 1, Code: "3208", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "32"},
		{Name: "盐城市", ProvinceCode: "32", Level: 1, Code: "3209", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "32"},
		{Name: "扬州市", ProvinceCode: "32", Level: 1, Code: "3210", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "32"},
		{Name: "镇江市", ProvinceCode: "32", Level: 1, Code: "3211", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "32"},
		{Name: "泰州市", ProvinceCode: "32", Level: 1, Code: "3212", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "32"},
		{Name: "宿迁市", ProvinceCode: "32", Level: 1, Code: "3213", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "32"},
		{Name: "杭州市", ProvinceCode: "33", Level: 1, Code: "3301", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "33"},
		{Name: "宁波市", ProvinceCode: "33", Level: 1, Code: "3302", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "33"},
		{Name: "温州市", ProvinceCode: "33", Level: 1, Code: "3303", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "33"},
		{Name: "嘉兴市", ProvinceCode: "33", Level: 1, Code: "3304", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "33"},
		{Name: "湖州市", ProvinceCode: "33", Level: 1, Code: "3305", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "33"},
		{Name: "绍兴市", ProvinceCode: "33", Level: 1, Code: "3306", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "33"},
		{Name: "金华市", ProvinceCode: "33", Level: 1, Code: "3307", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "33"},
		{Name: "衢州市", ProvinceCode: "33", Level: 1, Code: "3308", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "33"},
		{Name: "舟山市", ProvinceCode: "33", Level: 1, Code: "3309", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "33"},
		{Name: "台州市", ProvinceCode: "33", Level: 1, Code: "3310", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "33"},
		{Name: "丽水市", ProvinceCode: "33", Level: 1, Code: "3311", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "33"},
		{Name: "合肥市", ProvinceCode: "34", Level: 1, Code: "3401", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "34"},
		{Name: "芜湖市", ProvinceCode: "34", Level: 1, Code: "3402", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "34"},
		{Name: "蚌埠市", ProvinceCode: "34", Level: 1, Code: "3403", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "34"},
		{Name: "淮南市", ProvinceCode: "34", Level: 1, Code: "3404", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "34"},
		{Name: "马鞍山市", ProvinceCode: "34", Level: 1, Code: "3405", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "34"},
		{Name: "淮北市", ProvinceCode: "34", Level: 1, Code: "3406", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "34"},
		{Name: "铜陵市", ProvinceCode: "34", Level: 1, Code: "3407", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "34"},
		{Name: "安庆市", ProvinceCode: "34", Level: 1, Code: "3408", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "34"},
		{Name: "黄山市", ProvinceCode: "34", Level: 1, Code: "3410", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "34"},
		{Name: "滁州市", ProvinceCode: "34", Level: 1, Code: "3411", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "34"},
		{Name: "阜阳市", ProvinceCode: "34", Level: 1, Code: "3412", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "34"},
		{Name: "宿州市", ProvinceCode: "34", Level: 1, Code: "3413", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "34"},
		{Name: "六安市", ProvinceCode: "34", Level: 1, Code: "3415", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "34"},
		{Name: "亳州市", ProvinceCode: "34", Level: 1, Code: "3416", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "34"},
		{Name: "池州市", ProvinceCode: "34", Level: 1, Code: "3417", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "34"},
		{Name: "宣城市", ProvinceCode: "34", Level: 1, Code: "3418", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "34"},
		{Name: "福州市", ProvinceCode: "35", Level: 1, Code: "3501", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "35"},
		{Name: "厦门市", ProvinceCode: "35", Level: 1, Code: "3502", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "35"},
		{Name: "莆田市", ProvinceCode: "35", Level: 1, Code: "3503", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "35"},
		{Name: "三明市", ProvinceCode: "35", Level: 1, Code: "3504", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "35"},
		{Name: "泉州市", ProvinceCode: "35", Level: 1, Code: "3505", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "35"},
		{Name: "漳州市", ProvinceCode: "35", Level: 1, Code: "3506", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "35"},
		{Name: "南平市", ProvinceCode: "35", Level: 1, Code: "3507", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "35"},
		{Name: "龙岩市", ProvinceCode: "35", Level: 1, Code: "3508", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "35"},
		{Name: "宁德市", ProvinceCode: "35", Level: 1, Code: "3509", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "35"},
		{Name: "南昌市", ProvinceCode: "36", Level: 1, Code: "3601", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "36"},
		{Name: "景德镇市", ProvinceCode: "36", Level: 1, Code: "3602", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "36"},
		{Name: "萍乡市", ProvinceCode: "36", Level: 1, Code: "3603", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "36"},
		{Name: "九江市", ProvinceCode: "36", Level: 1, Code: "3604", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "36"},
		{Name: "新余市", ProvinceCode: "36", Level: 1, Code: "3605", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "36"},
		{Name: "鹰潭市", ProvinceCode: "36", Level: 1, Code: "3606", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "36"},
		{Name: "赣州市", ProvinceCode: "36", Level: 1, Code: "3607", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "36"},
		{Name: "吉安市", ProvinceCode: "36", Level: 1, Code: "3608", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "36"},
		{Name: "宜春市", ProvinceCode: "36", Level: 1, Code: "3609", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "36"},
		{Name: "抚州市", ProvinceCode: "36", Level: 1, Code: "3610", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "36"},
		{Name: "上饶市", ProvinceCode: "36", Level: 1, Code: "3611", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "36"},
		{Name: "济南市", ProvinceCode: "37", Level: 1, Code: "3701", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "37"},
		{Name: "青岛市", ProvinceCode: "37", Level: 1, Code: "3702", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "37"},
		{Name: "淄博市", ProvinceCode: "37", Level: 1, Code: "3703", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "37"},
		{Name: "枣庄市", ProvinceCode: "37", Level: 1, Code: "3704", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "37"},
		{Name: "东营市", ProvinceCode: "37", Level: 1, Code: "3705", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "37"},
		{Name: "烟台市", ProvinceCode: "37", Level: 1, Code: "3706", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "37"},
		{Name: "潍坊市", ProvinceCode: "37", Level: 1, Code: "3707", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "37"},
		{Name: "济宁市", ProvinceCode: "37", Level: 1, Code: "3708", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "37"},
		{Name: "泰安市", ProvinceCode: "37", Level: 1, Code: "3709", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "37"},
		{Name: "威海市", ProvinceCode: "37", Level: 1, Code: "3710", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "37"},
		{Name: "日照市", ProvinceCode: "37", Level: 1, Code: "3711", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "37"},
		{Name: "临沂市", ProvinceCode: "37", Level: 1, Code: "3713", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "37"},
		{Name: "德州市", ProvinceCode: "37", Level: 1, Code: "3714", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "37"},
		{Name: "聊城市", ProvinceCode: "37", Level: 1, Code: "3715", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "37"},
		{Name: "滨州市", ProvinceCode: "37", Level: 1, Code: "3716", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "37"},
		{Name: "菏泽市", ProvinceCode: "37", Level: 1, Code: "3717", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "37"},
		{Name: "郑州市", ProvinceCode: "41", Level: 1, Code: "4101", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "41"},
		{Name: "开封市", ProvinceCode: "41", Level: 1, Code: "4102", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "41"},
		{Name: "洛阳市", ProvinceCode: "41", Level: 1, Code: "4103", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "41"},
		{Name: "平顶山市", ProvinceCode: "41", Level: 1, Code: "4104", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "41"},
		{Name: "安阳市", ProvinceCode: "41", Level: 1, Code: "4105", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "41"},
		{Name: "鹤壁市", ProvinceCode: "41", Level: 1, Code: "4106", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "41"},
		{Name: "新乡市", ProvinceCode: "41", Level: 1, Code: "4107", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "41"},
		{Name: "焦作市", ProvinceCode: "41", Level: 1, Code: "4108", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "41"},
		{Name: "濮阳市", ProvinceCode: "41", Level: 1, Code: "4109", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "41"},
		{Name: "许昌市", ProvinceCode: "41", Level: 1, Code: "4110", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "41"},
		{Name: "漯河市", ProvinceCode: "41", Level: 1, Code: "4111", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "41"},
		{Name: "三门峡市", ProvinceCode: "41", Level: 1, Code: "4112", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "41"},
		{Name: "南阳市", ProvinceCode: "41", Level: 1, Code: "4113", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "41"},
		{Name: "商丘市", ProvinceCode: "41", Level: 1, Code: "4114", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "41"},
		{Name: "信阳市", ProvinceCode: "41", Level: 1, Code: "4115", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "41"},
		{Name: "周口市", ProvinceCode: "41", Level: 1, Code: "4116", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "41"},
		{Name: "驻马店市", ProvinceCode: "41", Level: 1, Code: "4117", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "41"},
		{Name: "省直辖县级行政区划", ProvinceCode: "41", Level: 1, Code: "4190", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "41"},
		{Name: "武汉市", ProvinceCode: "42", Level: 1, Code: "4201", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "42"},
		{Name: "黄石市", ProvinceCode: "42", Level: 1, Code: "4202", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "42"},
		{Name: "十堰市", ProvinceCode: "42", Level: 1, Code: "4203", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "42"},
		{Name: "宜昌市", ProvinceCode: "42", Level: 1, Code: "4205", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "42"},
		{Name: "襄阳市", ProvinceCode: "42", Level: 1, Code: "4206", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "42"},
		{Name: "鄂州市", ProvinceCode: "42", Level: 1, Code: "4207", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "42"},
		{Name: "荆门市", ProvinceCode: "42", Level: 1, Code: "4208", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "42"},
		{Name: "孝感市", ProvinceCode: "42", Level: 1, Code: "4209", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "42"},
		{Name: "荆州市", ProvinceCode: "42", Level: 1, Code: "4210", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "42"},
		{Name: "黄冈市", ProvinceCode: "42", Level: 1, Code: "4211", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "42"},
		{Name: "咸宁市", ProvinceCode: "42", Level: 1, Code: "4212", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "42"},
		{Name: "随州市", ProvinceCode: "42", Level: 1, Code: "4213", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "42"},
		{Name: "恩施土家族苗族自治州", ProvinceCode: "42", Level: 1, Code: "4228", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "42"},
		{Name: "省直辖县级行政区划", ProvinceCode: "42", Level: 1, Code: "4290", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "42"},
		{Name: "长沙市", ProvinceCode: "43", Level: 1, Code: "4301", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "43"},
		{Name: "株洲市", ProvinceCode: "43", Level: 1, Code: "4302", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "43"},
		{Name: "湘潭市", ProvinceCode: "43", Level: 1, Code: "4303", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "43"},
		{Name: "衡阳市", ProvinceCode: "43", Level: 1, Code: "4304", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "43"},
		{Name: "邵阳市", ProvinceCode: "43", Level: 1, Code: "4305", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "43"},
		{Name: "岳阳市", ProvinceCode: "43", Level: 1, Code: "4306", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "43"},
		{Name: "常德市", ProvinceCode: "43", Level: 1, Code: "4307", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "43"},
		{Name: "张家界市", ProvinceCode: "43", Level: 1, Code: "4308", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "43"},
		{Name: "益阳市", ProvinceCode: "43", Level: 1, Code: "4309", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "43"},
		{Name: "郴州市", ProvinceCode: "43", Level: 1, Code: "4310", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "43"},
		{Name: "永州市", ProvinceCode: "43", Level: 1, Code: "4311", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "43"},
		{Name: "怀化市", ProvinceCode: "43", Level: 1, Code: "4312", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "43"},
		{Name: "娄底市", ProvinceCode: "43", Level: 1, Code: "4313", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "43"},
		{Name: "湘西土家族苗族自治州", ProvinceCode: "43", Level: 1, Code: "4331", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "43"},
		{Name: "广州市", ProvinceCode: "44", Level: 1, Code: "4401", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "44"},
		{Name: "韶关市", ProvinceCode: "44", Level: 1, Code: "4402", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "44"},
		{Name: "深圳市", ProvinceCode: "44", Level: 1, Code: "4403", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "44"},
		{Name: "珠海市", ProvinceCode: "44", Level: 1, Code: "4404", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "44"},
		{Name: "汕头市", ProvinceCode: "44", Level: 1, Code: "4405", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "44"},
		{Name: "佛山市", ProvinceCode: "44", Level: 1, Code: "4406", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "44"},
		{Name: "江门市", ProvinceCode: "44", Level: 1, Code: "4407", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "44"},
		{Name: "湛江市", ProvinceCode: "44", Level: 1, Code: "4408", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "44"},
		{Name: "茂名市", ProvinceCode: "44", Level: 1, Code: "4409", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "44"},
		{Name: "肇庆市", ProvinceCode: "44", Level: 1, Code: "4412", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "44"},
		{Name: "惠州市", ProvinceCode: "44", Level: 1, Code: "4413", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "44"},
		{Name: "梅州市", ProvinceCode: "44", Level: 1, Code: "4414", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "44"},
		{Name: "汕尾市", ProvinceCode: "44", Level: 1, Code: "4415", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "44"},
		{Name: "河源市", ProvinceCode: "44", Level: 1, Code: "4416", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "44"},
		{Name: "阳江市", ProvinceCode: "44", Level: 1, Code: "4417", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "44"},
		{Name: "清远市", ProvinceCode: "44", Level: 1, Code: "4418", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "44"},
		{Name: "东莞市", ProvinceCode: "44", Level: 1, Code: "4419", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "44"},
		{Name: "中山市", ProvinceCode: "44", Level: 1, Code: "4420", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "44"},
		{Name: "潮州市", ProvinceCode: "44", Level: 1, Code: "4451", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "44"},
		{Name: "揭阳市", ProvinceCode: "44", Level: 1, Code: "4452", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "44"},
		{Name: "云浮市", ProvinceCode: "44", Level: 1, Code: "4453", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "44"},
		{Name: "南宁市", ProvinceCode: "45", Level: 1, Code: "4501", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "45"},
		{Name: "柳州市", ProvinceCode: "45", Level: 1, Code: "4502", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "45"},
		{Name: "桂林市", ProvinceCode: "45", Level: 1, Code: "4503", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "45"},
		{Name: "梧州市", ProvinceCode: "45", Level: 1, Code: "4504", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "45"},
		{Name: "北海市", ProvinceCode: "45", Level: 1, Code: "4505", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "45"},
		{Name: "防城港市", ProvinceCode: "45", Level: 1, Code: "4506", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "45"},
		{Name: "钦州市", ProvinceCode: "45", Level: 1, Code: "4507", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "45"},
		{Name: "贵港市", ProvinceCode: "45", Level: 1, Code: "4508", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "45"},
		{Name: "玉林市", ProvinceCode: "45", Level: 1, Code: "4509", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "45"},
		{Name: "百色市", ProvinceCode: "45", Level: 1, Code: "4510", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "45"},
		{Name: "贺州市", ProvinceCode: "45", Level: 1, Code: "4511", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "45"},
		{Name: "河池市", ProvinceCode: "45", Level: 1, Code: "4512", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "45"},
		{Name: "来宾市", ProvinceCode: "45", Level: 1, Code: "4513", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "45"},
		{Name: "崇左市", ProvinceCode: "45", Level: 1, Code: "4514", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "45"},
		{Name: "海口市", ProvinceCode: "46", Level: 1, Code: "4601", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "46"},
		{Name: "三亚市", ProvinceCode: "46", Level: 1, Code: "4602", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "46"},
		{Name: "三沙市", ProvinceCode: "46", Level: 1, Code: "4603", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "46"},
		{Name: "儋州市", ProvinceCode: "46", Level: 1, Code: "4604", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "46"},
		{Name: "省直辖县级行政区划", ProvinceCode: "46", Level: 1, Code: "4690", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "46"},
		{Name: "市辖区", ProvinceCode: "50", Level: 1, Code: "5001", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "50"},
		{Name: "县", ProvinceCode: "50", Level: 1, Code: "5002", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "50"},
		{Name: "成都市", ProvinceCode: "51", Level: 1, Code: "5101", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "51"},
		{Name: "自贡市", ProvinceCode: "51", Level: 1, Code: "5103", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "51"},
		{Name: "攀枝花市", ProvinceCode: "51", Level: 1, Code: "5104", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "51"},
		{Name: "泸州市", ProvinceCode: "51", Level: 1, Code: "5105", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "51"},
		{Name: "德阳市", ProvinceCode: "51", Level: 1, Code: "5106", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "51"},
		{Name: "绵阳市", ProvinceCode: "51", Level: 1, Code: "5107", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "51"},
		{Name: "广元市", ProvinceCode: "51", Level: 1, Code: "5108", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "51"},
		{Name: "遂宁市", ProvinceCode: "51", Level: 1, Code: "5109", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "51"},
		{Name: "内江市", ProvinceCode: "51", Level: 1, Code: "5110", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "51"},
		{Name: "乐山市", ProvinceCode: "51", Level: 1, Code: "5111", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "51"},
		{Name: "南充市", ProvinceCode: "51", Level: 1, Code: "5113", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "51"},
		{Name: "眉山市", ProvinceCode: "51", Level: 1, Code: "5114", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "51"},
		{Name: "宜宾市", ProvinceCode: "51", Level: 1, Code: "5115", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "51"},
		{Name: "广安市", ProvinceCode: "51", Level: 1, Code: "5116", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "51"},
		{Name: "达州市", ProvinceCode: "51", Level: 1, Code: "5117", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "51"},
		{Name: "雅安市", ProvinceCode: "51", Level: 1, Code: "5118", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "51"},
		{Name: "巴中市", ProvinceCode: "51", Level: 1, Code: "5119", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "51"},
		{Name: "资阳市", ProvinceCode: "51", Level: 1, Code: "5120", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "51"},
		{Name: "阿坝藏族羌族自治州", ProvinceCode: "51", Level: 1, Code: "5132", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "51"},
		{Name: "甘孜藏族自治州", ProvinceCode: "51", Level: 1, Code: "5133", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "51"},
		{Name: "凉山彝族自治州", ProvinceCode: "51", Level: 1, Code: "5134", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "51"},
		{Name: "贵阳市", ProvinceCode: "52", Level: 1, Code: "5201", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "52"},
		{Name: "六盘水市", ProvinceCode: "52", Level: 1, Code: "5202", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "52"},
		{Name: "遵义市", ProvinceCode: "52", Level: 1, Code: "5203", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "52"},
		{Name: "安顺市", ProvinceCode: "52", Level: 1, Code: "5204", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "52"},
		{Name: "毕节市", ProvinceCode: "52", Level: 1, Code: "5205", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "52"},
		{Name: "铜仁市", ProvinceCode: "52", Level: 1, Code: "5206", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "52"},
		{Name: "黔西南布依族苗族自治州", ProvinceCode: "52", Level: 1, Code: "5223", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "52"},
		{Name: "黔东南苗族侗族自治州", ProvinceCode: "52", Level: 1, Code: "5226", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "52"},
		{Name: "黔南布依族苗族自治州", ProvinceCode: "52", Level: 1, Code: "5227", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "52"},
		{Name: "昆明市", ProvinceCode: "53", Level: 1, Code: "5301", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "53"},
		{Name: "曲靖市", ProvinceCode: "53", Level: 1, Code: "5303", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "53"},
		{Name: "玉溪市", ProvinceCode: "53", Level: 1, Code: "5304", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "53"},
		{Name: "保山市", ProvinceCode: "53", Level: 1, Code: "5305", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "53"},
		{Name: "昭通市", ProvinceCode: "53", Level: 1, Code: "5306", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "53"},
		{Name: "丽江市", ProvinceCode: "53", Level: 1, Code: "5307", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "53"},
		{Name: "普洱市", ProvinceCode: "53", Level: 1, Code: "5308", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "53"},
		{Name: "临沧市", ProvinceCode: "53", Level: 1, Code: "5309", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "53"},
		{Name: "楚雄彝族自治州", ProvinceCode: "53", Level: 1, Code: "5323", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "53"},
		{Name: "红河哈尼族彝族自治州", ProvinceCode: "53", Level: 1, Code: "5325", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "53"},
		{Name: "文山壮族苗族自治州", ProvinceCode: "53", Level: 1, Code: "5326", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "53"},
		{Name: "西双版纳傣族自治州", ProvinceCode: "53", Level: 1, Code: "5328", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "53"},
		{Name: "大理白族自治州", ProvinceCode: "53", Level: 1, Code: "5329", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "53"},
		{Name: "德宏傣族景颇族自治州", ProvinceCode: "53", Level: 1, Code: "5331", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "53"},
		{Name: "怒江傈僳族自治州", ProvinceCode: "53", Level: 1, Code: "5333", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "53"},
		{Name: "迪庆藏族自治州", ProvinceCode: "53", Level: 1, Code: "5334", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "53"},
		{Name: "拉萨市", ProvinceCode: "54", Level: 1, Code: "5401", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "54"},
		{Name: "日喀则市", ProvinceCode: "54", Level: 1, Code: "5402", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "54"},
		{Name: "昌都市", ProvinceCode: "54", Level: 1, Code: "5403", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "54"},
		{Name: "林芝市", ProvinceCode: "54", Level: 1, Code: "5404", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "54"},
		{Name: "山南市", ProvinceCode: "54", Level: 1, Code: "5405", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "54"},
		{Name: "那曲市", ProvinceCode: "54", Level: 1, Code: "5406", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "54"},
		{Name: "阿里地区", ProvinceCode: "54", Level: 1, Code: "5425", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "54"},
		{Name: "西安市", ProvinceCode: "61", Level: 1, Code: "6101", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "61"},
		{Name: "铜川市", ProvinceCode: "61", Level: 1, Code: "6102", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "61"},
		{Name: "宝鸡市", ProvinceCode: "61", Level: 1, Code: "6103", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "61"},
		{Name: "咸阳市", ProvinceCode: "61", Level: 1, Code: "6104", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "61"},
		{Name: "渭南市", ProvinceCode: "61", Level: 1, Code: "6105", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "61"},
		{Name: "延安市", ProvinceCode: "61", Level: 1, Code: "6106", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "61"},
		{Name: "汉中市", ProvinceCode: "61", Level: 1, Code: "6107", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "61"},
		{Name: "榆林市", ProvinceCode: "61", Level: 1, Code: "6108", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "61"},
		{Name: "安康市", ProvinceCode: "61", Level: 1, Code: "6109", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "61"},
		{Name: "商洛市", ProvinceCode: "61", Level: 1, Code: "6110", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "61"},
		{Name: "兰州市", ProvinceCode: "62", Level: 1, Code: "6201", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "62"},
		{Name: "嘉峪关市", ProvinceCode: "62", Level: 1, Code: "6202", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "62"},
		{Name: "金昌市", ProvinceCode: "62", Level: 1, Code: "6203", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "62"},
		{Name: "白银市", ProvinceCode: "62", Level: 1, Code: "6204", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "62"},
		{Name: "天水市", ProvinceCode: "62", Level: 1, Code: "6205", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "62"},
		{Name: "武威市", ProvinceCode: "62", Level: 1, Code: "6206", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "62"},
		{Name: "张掖市", ProvinceCode: "62", Level: 1, Code: "6207", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "62"},
		{Name: "平凉市", ProvinceCode: "62", Level: 1, Code: "6208", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "62"},
		{Name: "酒泉市", ProvinceCode: "62", Level: 1, Code: "6209", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "62"},
		{Name: "庆阳市", ProvinceCode: "62", Level: 1, Code: "6210", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "62"},
		{Name: "定西市", ProvinceCode: "62", Level: 1, Code: "6211", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "62"},
		{Name: "陇南市", ProvinceCode: "62", Level: 1, Code: "6212", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "62"},
		{Name: "临夏回族自治州", ProvinceCode: "62", Level: 1, Code: "6229", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "62"},
		{Name: "甘南藏族自治州", ProvinceCode: "62", Level: 1, Code: "6230", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "62"},
		{Name: "西宁市", ProvinceCode: "63", Level: 1, Code: "6301", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "63"},
		{Name: "海东市", ProvinceCode: "63", Level: 1, Code: "6302", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "63"},
		{Name: "海北藏族自治州", ProvinceCode: "63", Level: 1, Code: "6322", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "63"},
		{Name: "黄南藏族自治州", ProvinceCode: "63", Level: 1, Code: "6323", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "63"},
		{Name: "海南藏族自治州", ProvinceCode: "63", Level: 1, Code: "6325", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "63"},
		{Name: "果洛藏族自治州", ProvinceCode: "63", Level: 1, Code: "6326", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "63"},
		{Name: "玉树藏族自治州", ProvinceCode: "63", Level: 1, Code: "6327", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "63"},
		{Name: "海西蒙古族藏族自治州", ProvinceCode: "63", Level: 1, Code: "6328", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "63"},
		{Name: "银川市", ProvinceCode: "64", Level: 1, Code: "6401", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "64"},
		{Name: "石嘴山市", ProvinceCode: "64", Level: 1, Code: "6402", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "64"},
		{Name: "吴忠市", ProvinceCode: "64", Level: 1, Code: "6403", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "64"},
		{Name: "固原市", ProvinceCode: "64", Level: 1, Code: "6404", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "64"},
		{Name: "中卫市", ProvinceCode: "64", Level: 1, Code: "6405", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "64"},
		{Name: "乌鲁木齐市", ProvinceCode: "65", Level: 1, Code: "6501", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "65"},
		{Name: "克拉玛依市", ProvinceCode: "65", Level: 1, Code: "6502", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "65"},
		{Name: "吐鲁番市", ProvinceCode: "65", Level: 1, Code: "6504", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "65"},
		{Name: "哈密市", ProvinceCode: "65", Level: 1, Code: "6505", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "65"},
		{Name: "昌吉回族自治州", ProvinceCode: "65", Level: 1, Code: "6523", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "65"},
		{Name: "博尔塔拉蒙古自治州", ProvinceCode: "65", Level: 1, Code: "6527", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "65"},
		{Name: "巴音郭楞蒙古自治州", ProvinceCode: "65", Level: 1, Code: "6528", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "65"},
		{Name: "阿克苏地区", ProvinceCode: "65", Level: 1, Code: "6529", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "65"},
		{Name: "克孜勒苏柯尔克孜自治州", ProvinceCode: "65", Level: 1, Code: "6530", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "65"},
		{Name: "喀什地区", ProvinceCode: "65", Level: 1, Code: "6531", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "65"},
		{Name: "和田地区", ProvinceCode: "65", Level: 1, Code: "6532", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "65"},
		{Name: "伊犁哈萨克自治州", ProvinceCode: "65", Level: 1, Code: "6540", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "65"},
		{Name: "塔城地区", ProvinceCode: "65", Level: 1, Code: "6542", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "65"},
		{Name: "阿勒泰地区", ProvinceCode: "65", Level: 1, Code: "6543", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "65"},
		{Name: "自治区直辖县级行政区划", ProvinceCode: "65", Level: 1, Code: "6590", Geocode: "", Latitude: "", Longitude: "", Sort: 0, ParentCode: "65"},
	}
	if err := db.Create(&entities).Error; err != nil {

		return ctx, errors.Wrap(err, "geo_cities表数据初始化失败!")
	}
	next := context.WithValue(ctx, i.InitializerName(), entities)
	return next, nil
}

func (i *initCity) DataInserted(ctx context.Context) bool {
	db, ok := ctx.Value("db").(*gorm.DB)
	if !ok {
		return false
	}
	if errors.Is(db.First(&model.City{}).Error, gorm.ErrRecordNotFound) {
		return false
	}
	return true
}
