package client

import (
	"errors"
	"strings"
	"sync"
	"testing"

	"github.com/flipped-aurora/gin-vue-admin/server/global"
	clientModel "github.com/flipped-aurora/gin-vue-admin/server/model/client"
	"github.com/glebarez/sqlite"
	"gorm.io/gorm"
)

func setupClientUserSecurityTestDB(t *testing.T) *gorm.DB {
	t.Helper()

	dsn := "file:" + strings.NewReplacer("/", "_", " ", "_", ":", "_").Replace(t.Name()) + "?mode=memory&cache=shared"
	db, err := gorm.Open(sqlite.Open(dsn), &gorm.Config{})
	if err != nil {
		t.Fatalf("open sqlite: %v", err)
	}
	sqlDB, err := db.DB()
	if err != nil {
		t.Fatalf("get sql db: %v", err)
	}
	sqlDB.SetMaxOpenConns(10)
	t.Cleanup(func() { _ = sqlDB.Close() })

	if err := db.AutoMigrate(&clientModel.ClientUser{}); err != nil {
		t.Fatalf("migrate client user: %v", err)
	}

	previousDB := global.GVA_DB
	global.GVA_DB = db
	t.Cleanup(func() { global.GVA_DB = previousDB })

	return db
}

func TestUpdateClientUserDoesNotWriteServiceManagedFields(t *testing.T) {
	db := setupClientUserSecurityTestDB(t)

	banned := false
	user := clientModel.ClientUser{
		Username:         "alice",
		Password:         "old-hash",
		Nickname:         "Alice",
		Point:            11,
		TryonPoint:       22,
		OpenID:           "openid-original",
		InviteCode:       "invite-a",
		InvitedBy:        7,
		SubOrderRewarded: true,
		Banned:           &banned,
	}
	if err := db.Create(&user).Error; err != nil {
		t.Fatalf("create user: %v", err)
	}

	newBanned := true
	service := ClientUserService{}
	if err := service.UpdateClientUser(clientModel.ClientUser{
		GVA_MODEL:        global.GVA_MODEL{ID: user.ID},
		Username:         "alice-new",
		Password:         "malicious-password",
		Nickname:         "Alice New",
		Point:            999,
		TryonPoint:       888,
		OpenID:           "openid-malicious",
		InviteCode:       "invite-malicious",
		InvitedBy:        99,
		SubOrderRewarded: false,
		Banned:           &newBanned,
	}); err != nil {
		t.Fatalf("update user: %v", err)
	}

	var updated clientModel.ClientUser
	if err := db.First(&updated, user.ID).Error; err != nil {
		t.Fatalf("load updated user: %v", err)
	}

	if updated.Username != "alice-new" || updated.Nickname != "Alice New" || updated.Banned == nil || !*updated.Banned {
		t.Fatalf("allowed profile fields were not updated: %+v", updated)
	}
	if updated.Password != "old-hash" || updated.Point != 11 || updated.TryonPoint != 22 || updated.OpenID != "openid-original" || updated.InviteCode != "invite-a" || updated.InvitedBy != 7 || !updated.SubOrderRewarded {
		t.Fatalf("service-managed fields changed unexpectedly: %+v", updated)
	}
}

func TestCreateClientUserSanitizesServiceManagedFields(t *testing.T) {
	db := setupClientUserSecurityTestDB(t)

	service := ClientUserService{}
	user := clientModel.ClientUser{
		Username:         "bob",
		Password:         "plain-password",
		Point:            100,
		TryonPoint:       200,
		OpenID:           "openid-injected",
		InviteCode:       "invite-injected",
		InvitedBy:        12,
		SubOrderRewarded: true,
	}
	if err := service.CreateClientUser(&user); err != nil {
		t.Fatalf("create user: %v", err)
	}

	var created clientModel.ClientUser
	if err := db.First(&created, user.ID).Error; err != nil {
		t.Fatalf("load created user: %v", err)
	}

	if created.Point != 0 || created.TryonPoint != 0 || created.OpenID != "" || created.InvitedBy != 0 || created.SubOrderRewarded {
		t.Fatalf("service-managed fields were not sanitized: %+v", created)
	}
	if created.InviteCode == "" || created.InviteCode == "invite-injected" {
		t.Fatalf("invite code was not generated by service: %q", created.InviteCode)
	}
	if created.Password == "plain-password" {
		t.Fatal("password was not hashed")
	}
}

func TestRegisterByPhoneSerializesDuplicatePhone(t *testing.T) {
	db := setupClientUserSecurityTestDB(t)

	service := ClientUserService{}
	const attempts = 12
	start := make(chan struct{})
	var wg sync.WaitGroup
	errs := make(chan error, attempts)

	for i := 0; i < attempts; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			<-start
			_, err := service.RegisterByPhone("+86", "13800138000", "secret", "")
			errs <- err
		}()
	}

	close(start)
	wg.Wait()
	close(errs)

	successes := 0
	duplicateErrors := 0
	for err := range errs {
		if err == nil {
			successes++
			continue
		}
		if errors.Is(err, gorm.ErrDuplicatedKey) || err.Error() == "phoneAlreadyRegistered" {
			duplicateErrors++
			continue
		}
		t.Fatalf("unexpected register error: %v", err)
	}

	if successes != 1 || duplicateErrors != attempts-1 {
		t.Fatalf("expected one success and %d duplicate errors, got successes=%d duplicates=%d", attempts-1, successes, duplicateErrors)
	}

	var count int64
	if err := db.Model(&clientModel.ClientUser{}).Where("area_code = ? AND phone = ?", "+86", "13800138000").Count(&count).Error; err != nil {
		t.Fatalf("count users: %v", err)
	}
	if count != 1 {
		t.Fatalf("expected exactly one registered user, got %d", count)
	}
}
